Fix type in shaders
Multiple occurrences of:
0:11(21): error: no matching function for call to `texture2DRect(sampler2DRect, vec4)'; candidates are:
0:11(21): error:    vec4 texture2DRect(sampler2DRect, vec2)

Due to the following or similar:
texture2DRect( osgOcean_FullColourMap, gl_TexCoord[0] );

gl_TexCoord[0] is a vec4.
gl_TexCoord[0].st selects the first two variables only.

Fixes: https://github.com/kbale/osgocean/issues/53
Signed-off-by: François Cami <fcami@fedoraproject.org>